name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Npm setup
        run: npm install

      - name: Build and check
        run: npm run build
